alkemyTech/OT275-server

src/main/java/com/alkemy/ong/application/repository/IRoleRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/entity/RoleEntity.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/IRoleSpringRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/RoleRepository.java
- RoleEntity
- IRoleRepository
- RoleRepository (implementation)
- IRoleSpringRepository
=> OT275-17: Added role and his respective repository

src/main/java/com/alkemy/ong/application/repository/ICategoryRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/entity/CategoryEntity.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/CategoryRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/ICategorySpringRepository.java
CategoryEntity
ICategoryEntity
CategoryRepository 
ICategorySpringRepository
- [ x] No testing required (only applies for tech task).
- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
=> OT275-19: Crear modelo y repositorio base de Categories

src/main/java/com/alkemy/ong/application/repository/IActivityRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/entity/ActivityEntity.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/ActivityRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/IActivitySpringRepository.java
- ActivyEntity
- IActivityRepository
- IActivitySpringRepository
- ActivityRepository
- [ x] No testing required (only applies for tech task).
- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
=> OT275-22: Create model and repository of Activities

src/main/java/com/alkemy/ong/application/repository/INewsRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/entity/NewsEntity.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/INewsSpringRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/NewsRepository.java
* INewsRepository
* NewsRepository
* INewsSpringRepository
* NewsEntity
* Added news-category relationship
=> OT275-20: Crear modelo y repositorio base de News

src/main/java/com/alkemy/ong/application/repository/IMemberRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/entity/MemberEntity.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/IMemberSpringRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/MemberRepository.java
- MemberEntity
- IMemberRepository
- IMemberSpringRepository
- MemberRepository
=> OT275-23: Create model and repository of Members

src/main/java/com/alkemy/ong/application/repository/ITestimonialRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/entity/TestimonialEntity.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/ITestimonialSpringRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/TestimonialRepository.java
Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.
* ...
* ...
* ....
=> OT275-21 Crear modelo y repositorio base de Testimonials

src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java
-Desabilité el csrf
-Todas las request deberán estar autentificadas
-Spring no usará ni creará sesiones
-agregó el filtro al método configure() 
* ...
* ...
* ....
=> OT275-74 : proteger rutas por JWT

src/main/java/com/alkemy/ong/infrastructure/database/entity/OrganizationEntity.java
Se agregaron los campos "facebookUrl","linkedInUrl" e "instagramUrl" a la entidad "organizations"
* ...
* ...
* ....
=> OT375-64 : Agregar campos de contacto a organizations

src/main/java/com/alkemy/ong/application/repository/ITestimonialRepository.java, src/main/java/com/alkemy/ong/application/service/DeleteTestimonialUseCaseService.java, src/main/java/com/alkemy/ong/application/service/usecase/IDeleteTestimonialUseCase.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/SpringBeanConfiguration.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/TestimonialRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/abstraction/ITestimonialSpringRepository.java, src/main/java/com/alkemy/ong/infrastructure/rest/resource/TestimonialResource.java, src/test/java/com/alkemy/ong/application/service/DeleteTestimonialUseCaseServiceTest.java
- Endpoint delete
- Delete Testimonial use case
=> OT275-68: Delete Testimonial endpoint

src/main/java/com/alkemy/ong/infrastructure/rest/mapper/UserRegisterMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/UserRegisterResponse.java
- UserRegisterResponse returns the user token.
=> OT275-50: Return token to user after registering on the site

src/main/java/com/alkemy/ong/application/repository/IOrganizationRepository.java, src/main/java/com/alkemy/ong/application/service/UpdateOrganizationUseCaseService.java, src/main/java/com/alkemy/ong/application/service/usecase/IUpdateOrganizationUseCase.java, src/main/java/com/alkemy/ong/domain/Organization.java, src/main/java/com/alkemy/ong/domain/SocialMedia.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/SpringBeanConfiguration.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java, src/main/java/com/alkemy/ong/infrastructure/database/mapper/OrganizationMapper.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/OrganizationRepository.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/OrganizationUpdateMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/SocialMediaMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/request/OrganizationUpdateRequest.java, src/main/java/com/alkemy/ong/infrastructure/rest/request/SocialMediaRequest.java, src/main/java/com/alkemy/ong/infrastructure/rest/resource/OrganizationResource.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/OrganizationUpdateResponse.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/SocialMediaResponse.java, src/test/java/com/alkemy/ong/application/service/UpdateOrganizationUseCaseServiceTest.java
I have added update organization feature and also added unit test.
- [xI have added tests that prove my fix is effective or that my feature works.
=> OT275-38: Endpoint para actualización de datos públicos de Organización

src/main/java/com/alkemy/ong/application/repository/ISlideRepository.java, src/main/java/com/alkemy/ong/application/service/GetSlideUseCaseService.java, src/main/java/com/alkemy/ong/application/service/usecase/IGetSlideUseCase.java, src/main/java/com/alkemy/ong/domain/Slide.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/SpringBeanConfiguration.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java, src/main/java/com/alkemy/ong/infrastructure/database/mapper/SlideEntityMapper.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/SlideRepository.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/GetSlideMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/resource/SlideResource.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/GetSlideResponse.java, src/test/java/com/alkemy/ong/application/service/GetSlideUseCaseServiceTest.java
An endpoint has been added to get all the details of a Slide provided by the ID.
=> OT275-57: Endpoint Detail Slides

src/main/java/com/alkemy/ong/application/repository/ISlideRepository.java, src/main/java/com/alkemy/ong/application/service/GetOrganizationUseCaseService.java, src/main/java/com/alkemy/ong/domain/Organization.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/SpringBeanConfiguration.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/SlideRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/abstraction/ISlideSpringRepository.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/GetOrganizationMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/SlideWithTextMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/GetOrganizationResponse.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/SlideWithTextResponse.java, src/test/java/com/alkemy/ong/application/service/GetOrganizationUseCaseServiceTest.java
I have added the slides list to the endpoint organization/public 
=> OT275-61: Agregar Slides a endpoint público

src/main/java/com/alkemy/ong/application/repository/IActivityRepository.java, src/main/java/com/alkemy/ong/application/service/UpdateActivityUseCaseService.java, src/main/java/com/alkemy/ong/application/service/usecase/IUpdateActivityUseCase.java, src/main/java/com/alkemy/ong/domain/Activity.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/SpringBeanConfiguration.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java, src/main/java/com/alkemy/ong/infrastructure/database/mapper/ActivityEntityMapper.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/ActivityRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/abstraction/IActivitySpringRepository.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/ActivityUpdateMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/request/ActivityUpdateRequest.java, src/main/java/com/alkemy/ong/infrastructure/rest/resource/ActivityResource.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/ActivityUpdateResponse.java
An endpoint has been added to update an activity provided by the ID.
=> OT275-52: Endpoint Update Activities

src/main/java/com/alkemy/ong/infrastructure/rest/mapper/GetOrganizationMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/SocialMediaMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/GetOrganizationResponse.java
I have added social links to organization/public endpoint response.
=> OT275-65:  Modificar endpoint público de organizations para devolver links de redes sociales

src/main/java/com/alkemy/ong/application/repository/INewsRepository.java, src/main/java/com/alkemy/ong/application/service/GetNewsUseCaseService.java, src/main/java/com/alkemy/ong/application/service/usecase/IGetNewsUseCase.java, src/main/java/com/alkemy/ong/domain/News.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/SpringBeanConfiguration.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java, src/main/java/com/alkemy/ong/infrastructure/database/mapper/NewsEntityMapper.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/NewsRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/abstraction/INewsSpringRepository.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/GetNewsMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/resource/NewsResource.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/GetNewsResponse.java, src/test/java/com/alkemy/ong/application/service/GetNewsUseCaseServiceTest.java, src/test/java/com/alkemy/ong/common/NewsBuilder.java
I have added get news by id endpoint and unit test
=> OT275-46: Endpoint Detalle Novedad

src/main/java/com/alkemy/ong/application/repository/ICategoryRepository.java, src/main/java/com/alkemy/ong/application/service/ListCategoryUseCaseService.java, src/main/java/com/alkemy/ong/application/service/usecase/IListCategoryUseCase.java, src/main/java/com/alkemy/ong/infrastructure/common/PaginatedResultsRetrieved.java, src/main/java/com/alkemy/ong/infrastructure/database/mapper/CategoryEntityMapper.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/CategoryRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/abstraction/ICategorySpringRepository.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/ListCategoryMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/resource/CategoryResource.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/ListCategoryResponse.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/PaginationResponse.java
**SUMMARY:** 
- implemented pagination on categories
* ...
* ...
=> OT275-81: Added pagination to categories

src/main/java/com/alkemy/ong/application/repository/IContactRepository.java, src/main/java/com/alkemy/ong/application/service/ListContactUseCaseService.java, src/main/java/com/alkemy/ong/application/service/usecase/IListContactUseCase.java, src/main/java/com/alkemy/ong/domain/Contact.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/SpringBeanConfiguration.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java, src/main/java/com/alkemy/ong/infrastructure/database/mapper/ContactEntityMapper.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/ContactRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/abstraction/IContactSpringRepository.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/GetContactMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/ListContactMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/resource/ContactResource.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/GetContactResponse.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/ListContactResponse.java
- Repositories implements findAll()
- Added Contact domain object
- Added service for listing Contacts
- Added response objects
- Added resource for listing Contacts
=> OT275-62: Endpoint for contact listing

README.md, src/main/java/com/alkemy/ong/domain/User.java, src/main/java/com/alkemy/ong/infrastructure/config/seeder/UserSeeder.java
- added seeder for standard and admin users
* ...
* ...
=> OT275-73: Create user seeder

src/main/java/com/alkemy/ong/application/repository/INewsRepository.java, src/main/java/com/alkemy/ong/application/service/GetNewsWithCommentsUseCaseService.java, src/main/java/com/alkemy/ong/application/service/usecase/IGetNewsWithCommentsUseCase.java, src/main/java/com/alkemy/ong/domain/News.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/SpringBeanConfiguration.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java, src/main/java/com/alkemy/ong/infrastructure/database/mapper/CommentEntityMapper.java, src/main/java/com/alkemy/ong/infrastructure/database/mapper/NewsEntityMapper.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/NewsRepository.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/abstraction/INewsSpringRepository.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/CommentMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/GetNewsWithCommentsMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/resource/NewsResource.java, src/main/java/com/alkemy/ong/infrastructure/rest/response/GetNewsWithCommentsResponse.java, src/test/java/com/alkemy/ong/common/NewsBuilder.java
-Added classes IGetNewsWithCommentsUseCase, GetNewsWithCommentsUseCaseService (Bean created), 
-Added mappers 
- Extend Domain News and create GetNewsWithCommentsResponse
- Added endpoint and method with security config
- Create Repository Query and methods 
* ...
* ...
=> OT275-80: List comments by newsId endpoint

pom.xml, src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java, src/main/resources/application.yaml, src/main/resources/static/documentation.yaml
Added basic documentation for the project, enabled access thru antMatchers
No tests were neede for this task
* ...
* ...
=> OT275-85: Agregar documentación con Swagger

src/main/resources/static/documentation.yaml
- Added documentation for get category 
* ...
* ...
* ....
=> OT275-86: Added documentation for categories

src/test/java/com/alkemy/ong/bigtest/BigTest.java, src/test/java/com/alkemy/ong/bigtest/category/CreateCategoryIntegrationTest.java
Added Integration tests for "POST /categories"
No additional configuration was needed to run these tests
* ....
=> OT275-98-Create: "POST / categories"

src/main/java/com/alkemy/ong/application/repository/ITestimonialRepository.java, src/main/java/com/alkemy/ong/application/service/testimonial/UpdateTestimonialUseCaseService.java, src/main/java/com/alkemy/ong/application/service/testimonial/usecase/IUpdateTestimonialUseCase.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/SpringBeanConfiguration.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java, src/main/java/com/alkemy/ong/infrastructure/database/mapper/TestimonialEntityMapper.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/TestimonialRepository.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/testimonial/UpdateTestimonialMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/request/testimonial/UpdateTestimonialRequest.java, src/main/java/com/alkemy/ong/infrastructure/rest/resource/TestimonialResource.java, src/test/java/com/alkemy/ong/application/service/UpdateTestimonialUseCaseServiceTest.java
- New endpoint to update Testimonials.
=> OT275-67: Endpoint Update Testimonials

src/main/resources/static/documentation.yaml
Added documentation for "auth/register", "auth/login" and "auth/me" endpoints.
=> OT275-90: Add documentation for Authentication.

src/main/resources/static/documentation.yaml
Applied draft recommendations to News Documentation
* ...
* ...
* ....
=> OT275-87: Agregar documentación a Novedades

src/main/resources/static/documentation.yaml
- added documentation for categories (all crud operations, following established patterns)
* ...
* ...
* ....
=> OT275-86: added documentation for categories.

src/main/java/com/alkemy/ong/application/repository/IMemberRepository.java, src/main/java/com/alkemy/ong/application/service/member/CreateMemberUseCaseService.java, src/main/java/com/alkemy/ong/application/service/member/usecase/ICreateMemberUseCase.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/SpringBeanConfiguration.java, src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java, src/main/java/com/alkemy/ong/infrastructure/database/mapper/MemberEntityMapper.java, src/main/java/com/alkemy/ong/infrastructure/database/repository/MemberRepository.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/member/CreateMemberMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/mapper/member/GetMemberMapper.java, src/main/java/com/alkemy/ong/infrastructure/rest/request/member/CreateMemberRequest.java, src/main/java/com/alkemy/ong/infrastructure/rest/resource/MemberResource.java, src/main/resources/static/documentation.yaml, src/test/java/com/alkemy/ong/application/service/CreateMemberUseCaseServiceTest.java
- New endpoint to add Members.
=> OT275-70: Endpoint Creation Members

src/main/resources/static/documentation.yaml, src/test/java/com/alkemy/ong/bigtest/news/AddNewsIntegrationTest.java
Added integration test for the endpoint POST /news
Integration tests were created
No extra configurations were needed to run these tetst
* ....
=> OT275-97-Add: "POST /news"

src/main/resources/static/documentation.yaml
Documentation for Testimonial Resource has been added.
=> OT275-89: Add Documentation for Testimonial Resource

src/test/java/com/alkemy/ong/bigtest/news/UpdateNewsIntegrationTest.java
Added integration test for the endpoint UPDATE /news/{id}
Integration tests were created
No extra configurations were needed to run these tests
* ....
=> OT275-97:  "PUT /news/{id}"

src/main/java/com/alkemy/ong/infrastructure/rest/request/testimonial/UpdateTestimonialRequest.java, src/test/java/com/alkemy/ong/application/service/CreateTestimonialUseCaseServiceTest.java, src/test/java/com/alkemy/ong/application/service/ListTestimonialUseCaseServiceTest.java, src/test/java/com/alkemy/ong/bigtest/BigTest.java, src/test/java/com/alkemy/ong/bigtest/testimonial/CreateTestimonialIntegrationTest.java, src/test/java/com/alkemy/ong/bigtest/testimonial/DeleteTestimonialIntegrationTest.java, src/test/java/com/alkemy/ong/bigtest/testimonial/ListTestimonialIntegrationTest.java, src/test/java/com/alkemy/ong/bigtest/testimonial/UpdateTestimonialIntegrationTest.java, src/test/java/com/alkemy/ong/builder/TestimonialBuilder.java
-Added POST testimonial integration test 
-Added GET testimonial integration test 
-Added UPDATE testimonial integration test 
-Added DELETE testimonial integration test 
* ...
* ...
=> OT275-99: integration test of /testimonials endpoint

src/test/java/com/alkemy/ong/bigtest/news/ListNewsIntegrationTest.java
Added integration test for the endpoint DELETE /news
Integration tests were created
No extra configurations were needed to run these test
* ....
=> OT275-97: "GET /news/"

src/main/java/com/alkemy/ong/infrastructure/rest/request/user/UpdateUserRequest.java, src/test/java/com/alkemy/ong/bigtest/BigTest.java, src/test/java/com/alkemy/ong/bigtest/user/ListUserIntegrationTest.java, src/test/java/com/alkemy/ong/bigtest/user/UpdateUserIntegrationTest.java, src/test/java/com/alkemy/ong/builder/UpdateUserRequestBuilder.java
Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.
* ...
* ...
* ....
=> OT275 -91: Update/List Users test
